-- INSERT UserNames
-- INSERT INTO user (username, password, name, surname, email, registration_date,detail, imgUrl) VALUES
-- ('Sumit7217', '$2a$11$267.npS/9E60NyMAcIdLketJCu4BiH1AX2/RHqwGuJfYF1HJA3Gnu', 'Sumit', 'Pathak',
-- 'pathaksumit721@gmail.com', '2024-05-11','Greater Noida, U.P. 201311', 'https://avatars.githubusercontent.com/u/98797074');
INSERT INTO user (username, password, name, surname, email, registration_date, imgUrl) VALUES
('Sumit123', '$2a$11$267.npS/9E60NyMAcIdLketJCu4BiH1AX2/RHqwGuJfYF1HJA3Gnu', 'Sumit', 'pathak',
 'sumitpathak721@gmail.com', '2018-09-10', 'https://avatars.githubusercontent.com/u/98797074?v=4'),
('demo', '$2a$11$.NNQgUXukpCuvB5nG.5XGO/NFOESgfPSqETlg5Pj2paBYmStZiucO', 'demo', 'test', 'demo@demo.com', '2018-09-10', 'https://media-exp1.licdn.com/dms/image/C4D03AQHLKGpueXacHA/profile-displayphoto-shrink_800_800/0/1552729654834?e=1673481600&v=beta&t=If15e82EfT7yR6mErCuhSADUaQQWlu-QoFdjFYbjWQk');
-- INSERT ROLES
INSERT INTO auth_user_group (username, auth_group) VALUES('Sumit123', 'ADMIN');
-- INSERT INTO auth_user_group (username, auth_group) VALUES('Sumit7217', 'ADMIN');
INSERT INTO auth_user_group (username, auth_group) VALUES('demo', 'USER');
-- INSERT tutors
INSERT INTO tutor (name, surname, email, description, detail, imgUrl) VALUES
( 'Shweta', 'Vishnoi', 'VishnoiShweta@hotmail.com', 'Physics', 'I am a Computer Engineer and I really like to share my knowledge and experience as a programmer. I have worked in numerous companies in Argentina, the United States and Spain. I have 2 years of experience teaching the following subjects: Networks, Java, JavaScript, C#, Visual Basic and SQL Server, both in companies and as private students.', 'https://i.ibb.co/J3rKw1y/Screenshot-2024-05-11-111027.png'),
( 'Rajat', 'Kumar', 'rajatkumar@gmail.com', 'Full Stack Development', 'I am an Assistant Professor of Full Stack development with knowledge of various Frameworks. He runs a YouTube channel where he teaches people around the world how to code.', 'https://media.licdn.com/dms/image/D5603AQFj-x6veQvauw/profile-displayphoto-shrink_200_200/0/1707536773827?e=1720656000&v=beta&t=esiW5rlKFsycOK4LKo2mCSlhYt3NoFWj7HY3Pt4UUtk'),
( 'Amit', 'Yadav', 'yadavamit@outlook.com', 'Computer Organization & Architecture', 'I learned Hardware and Software interaction the hard way, with lots of dead-ends, confusion, and knowledge gaps. I kept thinking, “It shouldn''t be this hard!” Now I teach students how to think and code like professional developers. My goal is to make it easier for you to become a developer.', 'https://i.ibb.co/8jWVpgQ/Screenshot-2024-05-11-111148.png');
-- INSERT courses
INSERT INTO course (name, description, tutorId, detail, difficulty, url, imgUrl) VALUES
( 'Semiconductor Physics part-1', 'Semiconductor Physics and Information Storage Part-1', 1, 'Introduction to semiconductor Physics in this lecture , Classical Free electron theory and quantum theory in solids is discussed.', 'Easy', 'https://youtu.be/yBWpoM8OeoI?si=R5ocb5WeGkleQiHu', 'https://i.ytimg.com/vi/wlIhEPIVzFE/hqdefault.jpg?sqp=-oaymwE2CNACELwBSFXyq4qpAygIARUAAIhCGAFwAcABBvABAfgB_gmAAtAFigIMCAAQARh_IB4oFzAP&rs=AOn4CLDJjYUvjwvVmm1I0klSmx6tjR28lg'),
( 'JavaScript Playlist', 'Introduction To JavaScript', 2, 'Playlist cover all concept of JavaScript. It covers basic concepts of scripting language and Client- Side Scripting and how do we run our JavaScript Code.', 'Easy', 'https://youtube.com/playlist?list=PL5nD5k_N5ksVvlwZTL_0p49hIFex7Nl8H&si=h7jfA1f7oSltqa5r', 'https://i.ytimg.com/vi/hmQi0nDJTdk/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLC2mxauyFCASyBQv0IOSxsQwdIZ3w'),
( 'Semiconductor Physics part-2', 'Semiconductor Physics and Information Storage Part-2', 1, 'Introduction to semiconductor Physics in this lecture , Classical Free electron theory and quantum theory in solids is discussed.', 'Easy', 'https://youtu.be/wlIhEPIVzFE?si=T07-y2VNd6wBcY9g', 'https://i.ytimg.com/vi/wlIhEPIVzFE/hqdefault.jpg?sqp=-oaymwE2CNACELwBSFXyq4qpAygIARUAAIhCGAFwAcABBvABAfgB_gmAAtAFigIMCAAQARh_IB4oFzAP&rs=AOn4CLDJjYUvjwvVmm1I0klSmx6tjR28lg'),
( 'Web Development basic', 'Web development fundamental', 2, 'This is Web development fundamental playlist.This tutorial explains the basics of HTML and CSS like its syntax and Various ways to insert CSS in your HTML Page.', 'Easy', 'https://youtu.be/hmQi0nDJTdk?si=yRfOAehwPd7RxxHM', 'https://i.ytimg.com/vi/gRKW8PWR2CA/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCs6ZFPi6c6qUffESRlMTe0iISYiQ'),
( 'Quantum Mechanism', 'Semiconductor Physics and Information Storage Part-2', 1, 'Introduction to semiconductor Physics in this lecture , Classical Free electron theory and quantum theory in solids is discussed.', 'Easy', 'https://youtu.be/vaIcI8wvCmg?si=qFc-2IvvJ56CHTey', 'https://i.ytimg.com/vi/vaIcI8wvCmg/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBmqW49Ugl0J-zgWAMvz8X6AmfySw'),
( 'Logic Gates', 'Computer Organization and Architecture', 3, 'Explain Basic Logic Gate and there internal Works', 'Easy', 'https://youtu.be/UyzBRl6lVxY?si=bQ-yfzOv1e1EEk__', 'https://i.ytimg.com/vi/UyzBRl6lVxY/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBEHq8RPhNzRRU6TREU2vHXac3cFQ'),
( 'Adder Subtractor Gate', 'Adder and Subtractor working', 3, 'Explain working adder and subtractor Gate and there internal Works', 'Easy', 'https://youtu.be/vB5eWU_XGZk?si=evVTm_M-MqpnlE2i', 'https://i.ytimg.com/vi/vB5eWU_XGZk/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLArPuN4oU2v5mnEVqJ-0XFL9oloyQ'),
( 'Addressing Mode in COA', ' immediate , direct, indirect, indexed, register & implied addressing mode',3, ' immediate , direct, indirect, indexed, register & implied addressing mode', 'Advanced', 'https://youtu.be/9xwotIUCq5M?si=W38-uBikGs6ZWFqN', 'https://i.ytimg.com/an_webp/9xwotIUCq5M/mqdefault_6s.webp?du=3000&sqp=COqP_LEG&rs=AOn4CLC4UmyK0JrBu0nPJR9BIiGHV6wGTg');
 -- INSERT enrollments
INSERT INTO enrollment (userId, courseId, date) VALUES ( 1, 3, '2024-05-11' );